arch:
  - amd64
  - ppc64le

addons:
  apt:
    packages: maven

language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk16

dist: trusty

# No need for preliminary install step.
install: true
#
# Run all integration tests.
script: 
  - "mvn --show-version --errors --batch-mode clean verify"
#
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - khmarbaise@apache.org
